### ISSUE TITLE
mnist_transferability example error

### ISSUE THREAD

**Issue by jinglin80** [IBM/adversarial-robustness-toolbox#130]
while trying to run the mnist_transferability example, the following error occurs:

Traceback (most recent call last):
  File "/data/jinglin/adversarial-robustness-toolbox/mnist_transferability.py", line 83, in <module>
    # Construct and train a convolutional neural network
  File "/data/jinglin/adversarial-robustness-toolbox/mnist_transferability.py", line 47, in cnn_mnist_tf
    
TypeError: __init__() got multiple values for argument 'output_ph'

**Comment by beat-buesser** [comment]
Hi @jinglin80 Thank you very much for bringing this to our attention. This example was not updated with the latest release, it is not an error in ART. I have pushed a fix to master branch.
