### ISSUE TITLE
Possible bug when loading PyTorch model.

### ISSUE THREAD

**Issue by Tomcli** [IBM/adversarial-robustness-toolbox#401]
**Describe the bug**
We are trying to load one of our model into the ART PyTorchClassifier. However, we are getting the below errors:
```
Traceback (most recent call last):
  File "/app/robustness_evaluation_fgsm_pytorch.py", line 105, in <module>
    epsilon=epsilon)
  File "/app/robustness.py", line 94, in robustness_evaluation
    classifier = PyTorchClassifier(clip_values, model, loss_fn, optimizer, input_shape, nb_classes)
  File "/opt/conda/lib/python3.6/site-packages/art/classifiers/pytorch.py", line 102, in __init__
    self._layer_names = self._model.get_layers
  File "/opt/conda/lib/python3.6/site-packages/art/classifiers/pytorch.py", line 664, in get_layers
    raise TypeError("The input model must inherit from `nn.Module`.")
TypeError: The input model must inherit from `nn.Module`.
```

Here is the PyTorch model we are using and it's using the nn.Module. Is there any way we could debug this?
```
import torch
import torch.utils.data
from torch.autograd import Variable
import torch.nn as nn



class ThreeLayerCNN(torch.nn.Module):
    def __init__(self):
        super(ThreeLayerCNN,self).__init__()
        self.conv1 = torch.nn.Conv2d(3,6,5)
        self.pool = torch.nn.MaxPool2d(2,2)
        self.conv2 = torch.nn.Conv2d(6,16,5)
        self.conv3 = torch.nn.Conv2d(16,16,6)
        self.fc1 = torch.nn.Linear(16*4*4,120)
        self.fc2 = torch.nn.Linear(120,2)

    def forward(self, x):
        x = self.pool(torch.nn.functional.relu(self.conv1(x)))
        x = self.pool(torch.nn.functional.relu(self.conv2(x)))
        x = self.pool(torch.nn.functional.relu(self.conv3(x)))
        x = x.view(-1,16*4*4)
        x = torch.nn.functional.relu(self.fc1(x))
        x = self.fc2(x)
        return x
```

**Expected behavior**
The model is able to load with the PyTorch library, so we expect it should able to load with the ART PyTorchClassifier.

**System information (please complete the following information):**
 - OS Darwin
 - Python version 3.6.4
 - ART version  1.2
 - PyTorch 1.3

**Comment by beat-buesser** [comment]
Hi @Tomcli Thank you for using ART! It looks like your error message is caused in this line of your error message: `classifier = PyTorchClassifier(clip_values, model, loss_fn, optimizer, input_shape, nb_classes)`.

The constructor of a PyTorchClassifier in ART 1.2 is:
```
class PyTorchClassifier(ClassifierNeuralNetwork, ClassifierGradients, Classifier):  # lgtm [py/missing-call-to-init]
    """
    This class implements a classifier with the PyTorch framework.
    """

    def __init__(
        self,
        model,
        loss,
        optimizer,
        input_shape,
        nb_classes,
        channel_index=1,
        clip_values=None,
        preprocessing_defences=None,
        postprocessing_defences=None,
        preprocessing=(0, 1),
        device_type="gpu",
    ):
```

It looks like you are providing the `clip_values` to the argument `model`, most likely this is the reason for the TypeError in your error message.

**Comment by Tomcli** [comment]
Thanks @beat-buesser, sorry I think my code was written a while ago and wasn't aware that PyTorchClassifier constructor had updated. It works now after I fix the bug in my code, thanks.
