### ISSUE TITLE
Adversarial Attacks failing when y is not none

### ISSUE THREAD

**Issue by hrosenberg** [IBM/adversarial-robustness-toolbox#483]
I'm running ART 1.3.1 with a tf2/keras classifier.  When running attack.generate(x=x, y=y) with projected_gradient_descent_numpy.py (y is not None),
I get a typeError.  The stacktrace and error description follow:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/base.py", line 223, in <module>
    run_config(args.config, args.from_file, args.check, args.mongo_host)
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/base.py", line 179, in run_config
    scenario.evaluate(config, mongo_host)
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/base.py", line 59, in evaluate
    results = self._evaluate(config)
  File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/audio_classification.py", line 122, in _evaluate
    x_adv = attack.generate(x=x, y=y)
  File "/opt/conda/lib/python3.7/site-packages/art/attacks/attack.py", line 74, in replacement_function
    return fdict[func_name](self, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/art/attacks/evasion/fast_gradient.py", line 171, in generate
    y = check_and_transform_label_format(y, self.estimator.nb_classes)
  File "/opt/conda/lib/python3.7/site-packages/art/utils.py", line 323, in check_and_transform_label_format
    labels = to_categorical(labels, nb_classes)
  File "/opt/conda/lib/python3.7/site-packages/art/utils.py", line 275, in to_categorical
    categorical = np.zeros((labels.shape[0], nb_classes), dtype=np.float32)
TypeError: 'method' object cannot be interpreted as an integer
```

**Comment by mathsinn** [comment]
@hrosenberg We'll need more information to investigate this. Can you please provide a complete minimum example for reproducing this error?

**Comment by hrosenberg** [comment]
We were able to resolve the issue.  Going from ART 1.2 to 1.3, it seems as though the nb_classes method was changed to an attribute contained within one or more of the following classes: (ClassifierNeuralNetwork, ClassifierGradients, Classifier) was changed to an class attribute.  Adding an @property decorator on our end fixed this.
